name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 0"}]
  # Trigger manually using github browser
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: jaylalakiya/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
